CREATE TABLE ROL (
	ROL_ID INT PRIMARY KEY,
	nombre VARCHAR(30)
);

CREATE TABLE SUPERVISOR (
	SUPERVISOR_ID INT PRIMARY KEY,
	ROL_ID INT,
	nombre VARCHAR(30),
	apellidos VARCHAR(50),
	password VARCHAR(50),
	email VARCHAR(50),
	estado BOOLEAN,
	CONSTRAINT FK_SUPERVISOR_ROL_ID FOREIGN KEY (ROL_ID)
	REFERENCES ROL (ROL_ID)
);


CREATE TABLE AGENTE (
	AGENTE_ID INT PRIMARY KEY,
	ROL_ID INT,
	nombre VARCHAR(30),
	apellidos VARCHAR(50),
	password VARCHAR(50),
	email VARCHAR(50),
	estado BOOLEAN,
	CONSTRAINT FK_AGENTE_ROL_ID FOREIGN KEY (ROL_ID)
	REFERENCES ROL (ROL_ID)
);


CREATE TABLE SUPERVISOR_ASIGNA_AGENTE(
	AGENTE_ID INT,
	SUPERVISOR_ID INT,
	PRIMARY KEY (AGENTE_ID, SUPERVISOR_ID),
	CONSTRAINT FK_SUPERVISOR_ASIGNA_AGENTE_AGENTE_ID FOREIGN KEY (AGENTE_ID)
	REFERENCES AGENTE (AGENTE_ID),
	CONSTRAINT FK_SUPERVISOR_ASIGNA_AGENTE_SUPERVISOR_ID FOREIGN KEY (SUPERVISOR_ID)
	REFERENCES SUPERVISOR (SUPERVISOR_ID)
);

CREATE TABLE AREA(
	AREA_ID INT PRIMARY KEY,
	nombre VARCHAR(30)
);


CREATE TABLE EMPRESA(
	NIT INT PRIMARY KEY,
	nombre VARCHAR(30),
	pais VARCHAR(30),
	ciudad VARCHAR(30),
	direccion VARCHAR(50),
	email VARCHAR(50)
);

CREATE TABLE CONTIENE_EMPRESA_AREA (
	NIT INT,
	AREA_ID INT,
	PRIMARY KEY(NIT, AREA_ID),
	CONSTRAINT FK_CONTIENE_EMPRESA_AREA_NIT FOREIGN KEY (NIT) REFERENCES EMPRESA(NIT),
	CONSTRAINT FK_CONTIENE_EMPRESA_AREA_AREA_ID FOREIGN KEY (AREA_ID) REFERENCES AREA (AREA_ID)
);

CREATE TABLE EMPLEADO (
	EMPLEADO_ID INT PRIMARY KEY,
	ROL_ID INT,
	AREA_ID INT,
	nombre VARCHAR(30),
	apellidos VARCHAR(50),
	password VARCHAR(50),
	email VARCHAR(50),
	estado BOOLEAN,
	CONSTRAINT FK_EMPLEADO_ROL_ID FOREIGN KEY (ROL_ID)
	REFERENCES ROL (ROL_ID),
	CONSTRAINT FK_EMPLEADO_AREA_ID FOREIGN KEY (AREA_ID)
	REFERENCES AREA (AREA_ID)
);

CREATE TABLE TICKET(
	TICKET_ID INT PRIMARY KEY,
	EMPLEADO_ID INT,
	AGENTE_ID INT,
	titulo VARCHAR(50),
	descripcion VARCHAR(100),
	imagenURL VARCHAR(256),
	fecha_inicio DATE,
	fecha_final DATE,
	estado BOOLEAN,
	CONSTRAINT FK_TICKET_EMPLEADO_ID FOREIGN KEY (EMPLEADO_ID)
	REFERENCES EMPLEADO (EMPLEADO_ID),
	CONSTRAINT FK_TICKET_AGENTE_ID FOREIGN KEY (AGENTE_ID)
	REFERENCES AGENTE (AGENTE_ID)
);

CREATE TABLE TELEFONO (
	NIT INT,
	telefono VARCHAR(10),
	PRIMARY KEY (NIT, telefono),
	CONSTRAINT FK_TELEFONO_NIT FOREIGN KEY (NIT)
	REFERENCES EMPRESA (NIT)
);


